const express=require('express');
const {Pool}=require('pg');
const bcrypt=require('bcryptjs');
const jwt=require('jsonwebtoken');
const multer=require('multer');
const QRCode=require('qrcode');
const PDFDocument=require('pdfkit');
const path=require('path');

const app=express();
const PORT=process.env.PORT||3000;
const JWT_SECRET=process.env.JWT_SECRET||'CHANGE_ME_GAJA_PRODUCTION_SECRET';
const DATABASE_URL=process.env.DATABASE_URL;
if(!DATABASE_URL){console.error('DATABASE_URL belum diatur. Hubungkan PostgreSQL/Supabase sebelum menjalankan GAJA Stock Control v4.');process.exit(1)}
const pool=new Pool({connectionString:DATABASE_URL,ssl:process.env.PGSSL==='disable'?false:{rejectUnauthorized:false},max:10,idleTimeoutMillis:30000,connectionTimeoutMillis:15000});

app.use(express.json({limit:'4mb'}));
app.use(express.static(path.join(__dirname,'public')));
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024},fileFilter:(req,file,cb)=>cb(null,/image\/(png|jpeg|webp)/.test(file.mimetype))});

async function initDb(){
  await pool.query(`
  CREATE TABLE IF NOT EXISTS users(
    id SERIAL PRIMARY KEY,name TEXT NOT NULL,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK(role IN ('admin','warehouse','viewer')),active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ DEFAULT NOW());
  CREATE TABLE IF NOT EXISTS categories(id SERIAL PRIMARY KEY,name TEXT UNIQUE NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW());
  CREATE TABLE IF NOT EXISTS items(
    id SERIAL PRIMARY KEY,code TEXT UNIQUE NOT NULL,name TEXT NOT NULL,category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
    brand TEXT DEFAULT '',stock INTEGER NOT NULL DEFAULT 0,min_stock INTEGER NOT NULL DEFAULT 0,unit TEXT DEFAULT 'Unit',condition TEXT DEFAULT 'Baik',
    location TEXT DEFAULT '',serial_no TEXT DEFAULT '',notes TEXT DEFAULT '',photo_mime TEXT DEFAULT '',photo_data BYTEA,
    asset_status TEXT DEFAULT 'Gudang',current_project TEXT DEFAULT '',current_holder TEXT DEFAULT '',updated_at TIMESTAMPTZ DEFAULT NOW());
  CREATE TABLE IF NOT EXISTS transactions(
    id SERIAL PRIMARY KEY,tx_date DATE NOT NULL,tx_type TEXT NOT NULL CHECK(tx_type IN ('IN','OUT')),item_id INTEGER NOT NULL REFERENCES items(id),
    qty INTEGER NOT NULL,stock_before INTEGER NOT NULL,stock_after INTEGER NOT NULL,source_target TEXT DEFAULT '',pic TEXT DEFAULT '',document_no TEXT DEFAULT '',
    notes TEXT DEFAULT '',created_by INTEGER REFERENCES users(id),created_at TIMESTAMPTZ DEFAULT NOW());
  CREATE TABLE IF NOT EXISTS transfer_requests(
    id SERIAL PRIMARY KEY,request_date DATE NOT NULL,item_id INTEGER NOT NULL REFERENCES items(id),qty INTEGER NOT NULL,project TEXT NOT NULL,receiver TEXT NOT NULL,
    document_no TEXT DEFAULT '',purpose TEXT DEFAULT '',status TEXT NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','APPROVED','REJECTED','RETURNED')),
    requested_by INTEGER NOT NULL REFERENCES users(id),approved_by INTEGER REFERENCES users(id),approval_note TEXT DEFAULT '',approved_at TIMESTAMPTZ,created_at TIMESTAMPTZ DEFAULT NOW());
  CREATE INDEX IF NOT EXISTS idx_items_category ON items(category_id);
  CREATE INDEX IF NOT EXISTS idx_tx_date ON transactions(tx_date);
  CREATE INDEX IF NOT EXISTS idx_req_status ON transfer_requests(status);
  `);
  const c=Number((await pool.query('SELECT COUNT(*)::int c FROM users')).rows[0].c);
  if(!c) await pool.query('INSERT INTO users(name,username,password_hash,role) VALUES($1,$2,$3,$4)',['Administrator','admin',bcrypt.hashSync('Admin123!',10),'admin']);
  for(const name of ['Power Tools','Hand Tools','Safety Equipment','Lifting Equipment','Electrical','Consumable']) await pool.query('INSERT INTO categories(name) VALUES($1) ON CONFLICT(name) DO NOTHING',[name]);
}

function auth(req,res,next){const h=req.headers.authorization||'';const t=h.startsWith('Bearer ')?h.slice(7):null;if(!t)return res.status(401).json({error:'Unauthorized'});try{req.user=jwt.verify(t,JWT_SECRET);next()}catch(e){res.status(401).json({error:'Session expired'})}}
const allow=(...roles)=>(req,res,next)=>roles.includes(req.user.role)?next():res.status(403).json({error:'Akses ditolak'});
const n=v=>Number(v||0);
function withPhotoPath(row){if(!row)return row;const {photo_data,...rest}=row;return {...rest,photo_path:row.photo_mime?`/api/items/${row.id}/photo-file`:''}}
async function itemRow(id,client=pool,lock=false){const q=`SELECT i.*,c.name category FROM items i LEFT JOIN categories c ON c.id=i.category_id WHERE i.id=$1${lock?' FOR UPDATE OF i':''}`;return withPhotoPath((await client.query(q,[id])).rows[0])}
async function logTx(client,{date,type,item,qty,target,pic,doc,notes,userId}){const before=n(item.stock),after=type==='IN'?before+qty:before-qty;if(after<0)throw new Error('Stok tidak cukup');await client.query('UPDATE items SET stock=$1,updated_at=NOW() WHERE id=$2',[after,item.id]);await client.query(`INSERT INTO transactions(tx_date,tx_type,item_id,qty,stock_before,stock_after,source_target,pic,document_no,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[date,type,item.id,qty,before,after,target||'',pic||'',doc||'',notes||'',userId]);return after}
async function inTx(fn){const c=await pool.connect();try{await c.query('BEGIN');const r=await fn(c);await c.query('COMMIT');return r}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
const ah=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);

app.post('/api/login',ah(async(req,res)=>{const {username,password}=req.body||{};const u=(await pool.query('SELECT * FROM users WHERE username=$1 AND active=TRUE',[username])).rows[0];if(!u||!bcrypt.compareSync(password||'',u.password_hash))return res.status(401).json({error:'Username atau password salah'});const user={id:u.id,name:u.name,username:u.username,role:u.role};res.json({token:jwt.sign(user,JWT_SECRET,{expiresIn:'12h'}),user})}));
app.get('/api/me',auth,(req,res)=>res.json({user:req.user}));
app.get('/api/dashboard',auth,ah(async(req,res)=>{const base=(await pool.query(`SELECT COUNT(*)::int item_count,COALESCE(SUM(stock),0)::int stock_total,COUNT(*) FILTER (WHERE stock<=min_stock)::int low_count,COUNT(*) FILTER (WHERE asset_status='Maintenance')::int maintenance_count FROM items`)).rows[0];const ym=new Date().toISOString().slice(0,7);const monthTx=(await pool.query("SELECT COUNT(*)::int c FROM transactions WHERE to_char(tx_date,'YYYY-MM')=$1",[ym])).rows[0].c;const pending=(await pool.query("SELECT COUNT(*)::int c FROM transfer_requests WHERE status='PENDING'")).rows[0].c;const recent=(await pool.query(`SELECT t.*,to_char(t.tx_date,'YYYY-MM-DD') tx_date,i.code,i.name item_name,u.name creator_name FROM transactions t JOIN items i ON i.id=t.item_id LEFT JOIN users u ON u.id=t.created_by ORDER BY t.tx_date DESC,t.id DESC LIMIT 8`)).rows;const alerts=(await pool.query(`SELECT i.id,i.code,i.name,i.stock,i.min_stock,i.unit,i.asset_status,c.name category FROM items i LEFT JOIN categories c ON c.id=i.category_id WHERE i.stock<=i.min_stock OR i.asset_status IN ('Maintenance','Rusak') ORDER BY CASE WHEN i.stock=0 THEN 0 ELSE 1 END,i.stock`)).rows;res.json({...base,monthTx,pending,recent,alerts})}));

app.get('/api/categories',auth,ah(async(req,res)=>res.json((await pool.query('SELECT c.*,COUNT(i.id)::int item_count FROM categories c LEFT JOIN items i ON i.category_id=c.id GROUP BY c.id ORDER BY c.name')).rows)));
app.post('/api/categories',auth,allow('admin','warehouse'),ah(async(req,res)=>{try{const r=await pool.query('INSERT INTO categories(name) VALUES($1) RETURNING id',[(req.body.name||'').trim()]);res.json({id:r.rows[0].id})}catch(e){res.status(400).json({error:'Kategori tidak valid / sudah ada'})}}));
app.put('/api/categories/:id',auth,allow('admin','warehouse'),ah(async(req,res)=>{try{await pool.query('UPDATE categories SET name=$1 WHERE id=$2',[(req.body.name||'').trim(),req.params.id]);res.json({ok:true})}catch(e){res.status(400).json({error:'Kategori tidak valid / sudah ada'})}}));
app.delete('/api/categories/:id',auth,allow('admin'),ah(async(req,res)=>{const c=(await pool.query('SELECT COUNT(*)::int c FROM items WHERE category_id=$1',[req.params.id])).rows[0].c;if(c)return res.status(400).json({error:'Kategori masih digunakan'});await pool.query('DELETE FROM categories WHERE id=$1',[req.params.id]);res.json({ok:true})}));

app.get('/api/items',auth,ah(async(req,res)=>{const rows=(await pool.query(`SELECT i.*,c.name category FROM items i LEFT JOIN categories c ON c.id=i.category_id ORDER BY i.name`)).rows.map(withPhotoPath);res.json(rows)}));
app.post('/api/items',auth,allow('admin','warehouse'),ah(async(req,res)=>{const b=req.body;if(!b.code?.trim()||!b.name?.trim())return res.status(400).json({error:'Kode dan nama alat wajib'});try{const r=await pool.query(`INSERT INTO items(code,name,category_id,brand,stock,min_stock,unit,condition,location,serial_no,notes,asset_status,current_project,current_holder) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING id`,[b.code.trim(),b.name.trim(),b.category_id||null,b.brand||'',n(b.stock),n(b.min_stock),b.unit||'Unit',b.condition||'Baik',b.location||'',b.serial_no||'',b.notes||'',b.asset_status||'Gudang',b.current_project||'',b.current_holder||'']);res.json({id:r.rows[0].id})}catch(e){res.status(400).json({error:'Kode alat sudah digunakan / data tidak valid'})}}));
app.put('/api/items/:id',auth,allow('admin','warehouse'),ah(async(req,res)=>{const b=req.body;try{await pool.query(`UPDATE items SET code=$1,name=$2,category_id=$3,brand=$4,stock=$5,min_stock=$6,unit=$7,condition=$8,location=$9,serial_no=$10,notes=$11,asset_status=$12,current_project=$13,current_holder=$14,updated_at=NOW() WHERE id=$15`,[b.code.trim(),b.name.trim(),b.category_id||null,b.brand||'',n(b.stock),n(b.min_stock),b.unit||'Unit',b.condition||'Baik',b.location||'',b.serial_no||'',b.notes||'',b.asset_status||'Gudang',b.current_project||'',b.current_holder||'',req.params.id]);res.json({ok:true})}catch(e){res.status(400).json({error:'Data item tidak valid / kode sudah digunakan'})}}));
app.delete('/api/items/:id',auth,allow('admin'),ah(async(req,res)=>{const c=(await pool.query('SELECT COUNT(*)::int c FROM transactions WHERE item_id=$1',[req.params.id])).rows[0].c;if(c)return res.status(400).json({error:'Item memiliki histori transaksi'});await pool.query('DELETE FROM items WHERE id=$1',[req.params.id]);res.json({ok:true})}));
app.post('/api/items/:id/photo',auth,allow('admin','warehouse'),upload.single('photo'),ah(async(req,res)=>{if(!req.file)return res.status(400).json({error:'File foto tidak valid'});await pool.query('UPDATE items SET photo_mime=$1,photo_data=$2,updated_at=NOW() WHERE id=$3',[req.file.mimetype,req.file.buffer,req.params.id]);res.json({photo_path:`/api/items/${req.params.id}/photo-file`})}));
app.get('/api/items/:id/photo-file',ah(async(req,res)=>{const r=(await pool.query('SELECT photo_mime,photo_data FROM items WHERE id=$1',[req.params.id])).rows[0];if(!r?.photo_data)return res.status(404).end();res.type(r.photo_mime||'image/jpeg');res.setHeader('Cache-Control','public, max-age=3600');res.send(r.photo_data)}));
app.get('/api/items/:id/qr',auth,ah(async(req,res)=>{const i=await itemRow(req.params.id);if(!i)return res.status(404).end();const base=process.env.PUBLIC_URL||`${req.protocol}://${req.get('host')}`;const payload=`${base}/?asset=${encodeURIComponent(i.code)}`;res.type('png');res.send(await QRCode.toBuffer(payload,{width:420,margin:2}))}));
app.get('/api/reports/inventory.pdf',auth,ah(async(req,res)=>{
  const q=String(req.query.q||'').trim().toLowerCase(),categoryId=req.query.category_id?Number(req.query.category_id):null,status=String(req.query.status||'').trim();
  const all=(await pool.query(`SELECT i.*,c.name category FROM items i LEFT JOIN categories c ON c.id=i.category_id ORDER BY COALESCE(c.name,''),i.name`)).rows.map(withPhotoPath);
  const items=all.filter(i=>(!q||[i.code,i.name,i.brand,i.category,i.location,i.current_project,i.current_holder,i.serial_no].join(' ').toLowerCase().includes(q))&&(!categoryId||Number(i.category_id)===categoryId)&&(!status||i.asset_status===status));
  const totalStock=items.reduce((a,b)=>a+n(b.stock),0),low=items.filter(i=>n(i.stock)<=n(i.min_stock)).length;
  const counts={};items.forEach(i=>counts[i.asset_status||'Lainnya']=(counts[i.asset_status||'Lainnya']||0)+1);
  const doc=new PDFDocument({size:'A4',layout:'landscape',margin:28,bufferPages:true,info:{Title:'GAJA Master Inventory Report',Author:'PT Graha Adhi Jaya Abadi',Subject:'Master Inventaris Alat Kerja'}});
  res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition','attachment; filename=GAJA_Master_Inventaris_Alat.pdf');doc.pipe(res);
  const W=doc.page.width,H=doc.page.height,L=28,R=W-28,navy='#163a5f',dark='#172033',muted='#66758a',green='#15735b',orange='#b66b00',red='#b42318',line='#dce5ed';
  const generated=new Date().toLocaleString('id-ID',{timeZone:'Asia/Jakarta'});
  function header(){doc.save().rect(0,0,W,68).fill(navy).restore();doc.fillColor('#fff').font('Helvetica-Bold').fontSize(18).text('GAJA',L,17,{width:60});doc.fontSize(10).text('PT GRAHA ADHI JAYA ABADI',95,16,{width:330});doc.font('Helvetica').fontSize(7.5).text('Warehouse & Asset Control System',95,32,{width:330});doc.font('Helvetica-Bold').fontSize(10).text('MASTER INVENTORY REPORT - WORK TOOLS',L,49,{width:R-L,align:'right'});doc.fillColor(dark)}
  function footer(pageNum){doc.moveTo(L,H-27).lineTo(R,H-27).strokeColor(line).stroke();doc.font('Helvetica').fontSize(6.8).fillColor(muted).text(`GAJA/WH/INV  |  Rev. 00  |  Generated ${generated}`,L,H-20,{width:R-L-65});doc.text(`Page ${pageNum}`,R-55,H-20,{width:55,align:'right'});doc.fillColor(dark)}
  function kpi(x,y,w,label,value,accent){doc.roundedRect(x,y,w,48,5).fillAndStroke('#fff',line);doc.rect(x,y,4,48).fill(accent);doc.fillColor(muted).font('Helvetica-Bold').fontSize(6.5).text(label.toUpperCase(),x+11,y+9,{width:w-18});doc.fillColor(dark).fontSize(16).text(String(value),x+11,y+20,{width:w-18});}
  function tableHead(y,widths,headers){doc.rect(L,y,widths.reduce((a,b)=>a+b,0),21).fill(navy);let x=L;headers.forEach((h,i)=>{doc.fillColor('#fff').font('Helvetica-Bold').fontSize(6.7).text(h,x+3,y+6,{width:widths[i]-6,height:14,ellipsis:true});x+=widths[i]});doc.fillColor(dark);return y+21}
  header();
  doc.y=82;doc.font('Helvetica-Bold').fontSize(13).fillColor(navy).text('Master Inventaris Alat Kerja');
  doc.font('Helvetica').fontSize(7.5).fillColor(muted).text(`Dicetak: ${generated}  |  Filter: ${q?`Pencarian "${q}"`: 'Semua data'}${categoryId?' • kategori terpilih':''}${status?` • Status ${status}`:''}`);
  const ky=111, gap=8, kw=(R-L-gap*4)/5;kpi(L,ky,kw,'Jenis Alat',items.length,navy);kpi(L+(kw+gap),ky,kw,'Total Stok',totalStock,green);kpi(L+2*(kw+gap),ky,kw,'Perlu Restock',low,low?red:green);kpi(L+3*(kw+gap),ky,kw,'Di Project',counts.Project||0,orange);kpi(L+4*(kw+gap),ky,kw,'Maintenance/Rusak',(counts.Maintenance||0)+(counts.Rusak||0),red);
  doc.y=171;doc.font('Helvetica-Bold').fontSize(9).fillColor(navy).text('Daftar Inventaris');doc.moveDown(.3);
  const headers=['No','Kode','Nama Alat','Kategori','Stok','Min','Sat.','Status','Lokasi','Kondisi','Project / Holder'];
  const widths=[24,60,118,86,38,32,34,62,76,58,119];
  let y=doc.y;y=tableHead(y,widths,headers);
  const rowH=22;
  items.forEach((i,idx)=>{if(y+rowH>H-36){doc.addPage();header();y=86;y=tableHead(y,widths,headers)}if(idx%2===0)doc.rect(L,y,widths.reduce((a,b)=>a+b,0),rowH).fill('#f7f9fb');let x=L;const project=[i.current_project,i.current_holder].filter(Boolean).join(' / ')||'-';const row=[idx+1,i.code,i.name,i.category||'-',i.stock,i.min_stock,i.unit,i.asset_status||'-',i.location||'-',i.condition||'-',project];row.forEach((v,c)=>{let color=dark;if(c===7){if(v==='Rusak')color=red;else if(v==='Maintenance')color=orange;else if(v==='Gudang')color=green}doc.fillColor(color).font(c===1||c===2?'Helvetica-Bold':'Helvetica').fontSize(6.5).text(String(v??'-'),x+3,y+5,{width:widths[c]-6,height:rowH-7,ellipsis:true});x+=widths[c]});doc.strokeColor('#e5ebf1').moveTo(L,y+rowH).lineTo(R,y+rowH).stroke();y+=rowH});
  if(!items.length){doc.font('Helvetica').fontSize(9).fillColor(muted).text('Tidak ada data inventaris yang sesuai filter.',L,y+12)}
  doc.addPage();header();doc.y=92;doc.font('Helvetica-Bold').fontSize(12).fillColor(navy).text('Ringkasan Status Inventaris');doc.moveDown(.7);
  const statusRows=Object.entries(counts).sort((a,b)=>b[1]-a[1]);if(statusRows.length){statusRows.forEach(([st,c],idx)=>{const yy=doc.y;doc.roundedRect(L,yy,R-L,28,4).fillAndStroke(idx%2===0?'#f7f9fb':'#fff',line);doc.fillColor(dark).font('Helvetica-Bold').fontSize(8).text(st,L+10,yy+9,{width:200});doc.fontSize(8).text(String(c),R-80,yy+9,{width:60,align:'right'});doc.y=yy+34})}else doc.font('Helvetica').fontSize(8).fillColor(muted).text('Belum ada data inventaris.');
  doc.y=Math.max(doc.y,360);doc.font('Helvetica-Bold').fontSize(10).fillColor(navy).text('Approval');doc.moveDown(.8);const sy=doc.y,sw=(R-L-40)/3;[['Prepared by','Warehouse'],['Checked by','HSE / Project'],['Approved by','Management']].forEach((a,idx)=>{const x=L+idx*(sw+20);doc.roundedRect(x,sy,sw,105,5).strokeColor(line).stroke();doc.fillColor(muted).font('Helvetica-Bold').fontSize(7).text(a[0].toUpperCase(),x+10,sy+10,{width:sw-20,align:'center'});doc.fillColor(dark).font('Helvetica-Bold').fontSize(8).text(a[1],x+10,sy+26,{width:sw-20,align:'center'});doc.moveTo(x+25,sy+82).lineTo(x+sw-25,sy+82).strokeColor(line).stroke();doc.font('Helvetica').fontSize(6.5).fillColor(muted).text('Name / Signature / Date',x+10,sy+87,{width:sw-20,align:'center'})});
  const pages=doc.bufferedPageRange();for(let i=0;i<pages.count;i++){doc.switchToPage(i);footer(i+1)}doc.end();
}));

app.get('/api/transactions',auth,ah(async(req,res)=>res.json((await pool.query(`SELECT t.*,to_char(t.tx_date,'YYYY-MM-DD') tx_date,i.code,i.name item_name,i.unit,u.name creator_name FROM transactions t JOIN items i ON i.id=t.item_id LEFT JOIN users u ON u.id=t.created_by ORDER BY t.tx_date DESC,t.id DESC`)).rows)));
app.post('/api/transactions',auth,allow('admin','warehouse'),ah(async(req,res)=>{const b=req.body,qty=n(b.qty);try{const after=await inTx(async c=>{const i=(await c.query('SELECT * FROM items WHERE id=$1 FOR UPDATE',[b.item_id])).rows[0];if(!i||qty<=0)throw new Error('Data transaksi tidak valid');const a=await logTx(c,{date:b.tx_date,type:b.tx_type,item:i,qty,target:b.source_target,pic:b.pic,doc:b.document_no,notes:b.notes,userId:req.user.id});if(b.tx_type==='IN'&&b.set_status)await c.query('UPDATE items SET asset_status=$1,current_project=$2,current_holder=$3 WHERE id=$4',[b.set_status,b.set_status==='Project'?(b.source_target||''):'',b.set_status==='Dipinjam'?(b.pic||''):'',i.id]);return a});res.json({stock_after:after})}catch(e){res.status(400).json({error:e.message})}}));

app.get('/api/transfers',auth,ah(async(req,res)=>res.json((await pool.query(`SELECT r.*,to_char(r.request_date,'YYYY-MM-DD') request_date,i.code,i.name item_name,i.unit,ru.name requester,au.name approver FROM transfer_requests r JOIN items i ON i.id=r.item_id LEFT JOIN users ru ON ru.id=r.requested_by LEFT JOIN users au ON au.id=r.approved_by ORDER BY r.id DESC`)).rows)));
app.post('/api/transfers',auth,allow('admin','warehouse'),ah(async(req,res)=>{const b=req.body;if(!b.item_id||n(b.qty)<=0||!b.project?.trim()||!b.receiver?.trim())return res.status(400).json({error:'Alat, jumlah, project, dan penerima wajib diisi'});const i=(await pool.query('SELECT stock FROM items WHERE id=$1',[b.item_id])).rows[0];if(!i||n(b.qty)>n(i.stock))return res.status(400).json({error:'Stok tidak mencukupi'});const r=await pool.query(`INSERT INTO transfer_requests(request_date,item_id,qty,project,receiver,document_no,purpose,requested_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id`,[b.request_date,b.item_id,n(b.qty),b.project.trim(),b.receiver.trim(),b.document_no||'',b.purpose||'',req.user.id]);res.json({id:r.rows[0].id})}));
app.post('/api/transfers/:id/approve',auth,allow('admin'),ah(async(req,res)=>{try{await inTx(async c=>{const r=(await c.query('SELECT * FROM transfer_requests WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!r||r.status!=='PENDING')throw new Error('Request tidak dapat diproses');const i=(await c.query('SELECT * FROM items WHERE id=$1 FOR UPDATE',[r.item_id])).rows[0];if(n(r.qty)>n(i.stock))throw new Error('Stok saat approval tidak mencukupi');await logTx(c,{date:r.request_date,type:'OUT',item:i,qty:n(r.qty),target:r.project,pic:r.receiver,doc:r.document_no,notes:'Approved handover: '+r.purpose,userId:req.user.id});await c.query("UPDATE transfer_requests SET status='APPROVED',approved_by=$1,approval_note=$2,approved_at=NOW() WHERE id=$3",[req.user.id,req.body.note||'',r.id]);await c.query("UPDATE items SET asset_status='Project',current_project=$1,current_holder=$2 WHERE id=$3",[r.project,r.receiver,r.item_id])});res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}}));
app.post('/api/transfers/:id/reject',auth,allow('admin'),ah(async(req,res)=>{const r=await pool.query("UPDATE transfer_requests SET status='REJECTED',approved_by=$1,approval_note=$2,approved_at=NOW() WHERE id=$3 AND status='PENDING' RETURNING id",[req.user.id,req.body.note||'',req.params.id]);if(!r.rowCount)return res.status(400).json({error:'Request tidak dapat ditolak'});res.json({ok:true})}));
app.post('/api/transfers/:id/return',auth,allow('admin','warehouse'),ah(async(req,res)=>{try{await inTx(async c=>{const r=(await c.query('SELECT * FROM transfer_requests WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!r||r.status!=='APPROVED')throw new Error('Request belum approved / sudah dikembalikan');const i=(await c.query('SELECT * FROM items WHERE id=$1 FOR UPDATE',[r.item_id])).rows[0];await logTx(c,{date:req.body.return_date,type:'IN',item:i,qty:n(r.qty),target:'Gudang',pic:req.user.name,doc:r.document_no,notes:'Pengembalian dari '+r.project,userId:req.user.id});await c.query("UPDATE transfer_requests SET status='RETURNED' WHERE id=$1",[r.id]);await c.query("UPDATE items SET asset_status='Gudang',current_project='',current_holder='' WHERE id=$1",[r.item_id])});res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}}));

app.get('/api/users',auth,allow('admin'),ah(async(req,res)=>res.json((await pool.query('SELECT id,name,username,role,active,created_at FROM users ORDER BY name')).rows)));
app.post('/api/users',auth,allow('admin'),ah(async(req,res)=>{const b=req.body;if(!b.name||!b.username||!b.password)return res.status(400).json({error:'Data user belum lengkap'});try{const r=await pool.query('INSERT INTO users(name,username,password_hash,role) VALUES($1,$2,$3,$4) RETURNING id',[b.name,b.username,bcrypt.hashSync(b.password,10),b.role]);res.json({id:r.rows[0].id})}catch(e){res.status(400).json({error:'Username sudah digunakan'})}}));
app.put('/api/users/:id',auth,allow('admin'),ah(async(req,res)=>{const b=req.body;if(b.password)await pool.query('UPDATE users SET name=$1,role=$2,active=$3,password_hash=$4 WHERE id=$5',[b.name,b.role,!!b.active,bcrypt.hashSync(b.password,10),req.params.id]);else await pool.query('UPDATE users SET name=$1,role=$2,active=$3 WHERE id=$4',[b.name,b.role,!!b.active,req.params.id]);res.json({ok:true})}));

async function monthlyReportData(month){
  const tx=(await pool.query(`SELECT t.*,to_char(t.tx_date,'YYYY-MM-DD') tx_date,i.code,i.name item_name,i.unit,c.name category,u.name creator FROM transactions t JOIN items i ON i.id=t.item_id LEFT JOIN categories c ON c.id=i.category_id LEFT JOIN users u ON u.id=t.created_by WHERE to_char(t.tx_date,'YYYY-MM')=$1 ORDER BY t.tx_date,t.id`,[month])).rows;
  const items=(await pool.query(`SELECT i.*,c.name category FROM items i LEFT JOIN categories c ON c.id=i.category_id ORDER BY COALESCE(c.name,''),i.name`)).rows.map(withPhotoPath);
  const transfers=(await pool.query(`SELECT r.*,to_char(r.request_date,'YYYY-MM-DD') request_date,i.code,i.name item_name,i.unit,ru.name requester,au.name approver FROM transfer_requests r JOIN items i ON i.id=r.item_id LEFT JOIN users ru ON ru.id=r.requested_by LEFT JOIN users au ON au.id=r.approved_by WHERE to_char(r.request_date,'YYYY-MM')=$1 ORDER BY r.request_date,r.id`,[month])).rows;
  const totalIn=tx.filter(x=>x.tx_type==='IN').reduce((a,b)=>a+n(b.qty),0),totalOut=tx.filter(x=>x.tx_type==='OUT').reduce((a,b)=>a+n(b.qty),0);
  const low=items.filter(x=>n(x.stock)<=n(x.min_stock)),maint=items.filter(x=>x.asset_status==='Maintenance'),broken=items.filter(x=>x.asset_status==='Rusak'),project=items.filter(x=>x.asset_status==='Project'),borrowed=items.filter(x=>x.asset_status==='Dipinjam');
  const categories={};tx.forEach(t=>{const k=t.category||'Tanpa Kategori';if(!categories[k])categories[k]={category:k,in_qty:0,out_qty:0};categories[k][t.tx_type==='IN'?'in_qty':'out_qty']+=n(t.qty)});
  const topOut=Object.values(tx.filter(t=>t.tx_type==='OUT').reduce((a,t)=>{if(!a[t.item_id])a[t.item_id]={code:t.code,name:t.item_name,unit:t.unit,qty:0};a[t.item_id].qty+=n(t.qty);return a},{})).sort((a,b)=>b.qty-a.qty).slice(0,10);
  return {tx,items,transfers,totalIn,totalOut,low,maint,broken,project,borrowed,categories:Object.values(categories).sort((a,b)=>a.category.localeCompare(b.category)),topOut};
}
function monthLabel(month){const [y,m]=month.split('-').map(Number);const names=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];return `${names[m-1]||m} ${y}`}
function fmtDateID(s){if(!s)return '-';const [y,m,d]=String(s).slice(0,10).split('-');return `${d}/${m}/${y}`}
app.get('/api/reports/monthly-summary',auth,ah(async(req,res)=>{const month=req.query.month||new Date().toISOString().slice(0,7);if(!/^\d{4}-\d{2}$/.test(month))return res.status(400).json({error:'Periode tidak valid'});const d=await monthlyReportData(month);res.json({period:month,label:monthLabel(month),kpi:{itemTypes:d.items.length,totalStock:d.items.reduce((a,b)=>a+n(b.stock),0),totalIn:d.totalIn,totalOut:d.totalOut,lowStock:d.low.length,project:d.project.length,borrowed:d.borrowed.length,maintenance:d.maint.length,broken:d.broken.length,transactions:d.tx.length},categories:d.categories,topOut:d.topOut,lowStock:d.low.slice(0,20).map(i=>({code:i.code,name:i.name,stock:i.stock,min_stock:i.min_stock,unit:i.unit,category:i.category})),projects:d.items.filter(i=>i.asset_status==='Project'||i.asset_status==='Dipinjam').map(i=>({code:i.code,name:i.name,status:i.asset_status,project:i.current_project,holder:i.current_holder,stock:i.stock,unit:i.unit})),transfers:d.transfers.slice(0,25).map(r=>({date:r.request_date,code:r.code,name:r.item_name,qty:r.qty,unit:r.unit,project:r.project,receiver:r.receiver,status:r.status}))})}));

app.get('/api/reports/monthly.pdf',auth,ah(async(req,res)=>{
  const month=req.query.month||new Date().toISOString().slice(0,7);if(!/^\d{4}-\d{2}$/.test(month))return res.status(400).json({error:'Periode tidak valid'});
  const d=await monthlyReportData(month),label=monthLabel(month),[yy,mm]=month.split('-'),docNo=`GAJA/WH/MR/${yy}/${mm}`;
  const doc=new PDFDocument({size:'A4',margin:34,bufferPages:true,info:{Title:`Monthly Warehouse & Tools Report - ${label}`,Author:'PT Graha Adhi Jaya Abadi',Subject:'Warehouse Stock Control'}});res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`attachment; filename=GAJA_Monthly_Warehouse_Report_${month}.pdf`);doc.pipe(res);
  const W=doc.page.width,H=doc.page.height,L=34,R=W-34,blue='#163a5f',light='#eaf1f7',dark='#172033',muted='#66758a',green='#15735b',orange='#b66b00',red='#b42318';
  function header(title='MONTHLY WAREHOUSE & TOOLS REPORT'){doc.save().rect(0,0,W,76).fill(blue).restore();doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(17).text('GAJA',L,20,{width:55});doc.fontSize(10).text('PT GRAHA ADHI JAYA ABADI',95,18,{width:300});doc.font('Helvetica').fontSize(7.5).text('Warehouse & Asset Control System',95,34,{width:300});doc.font('Helvetica-Bold').fontSize(9).text(title,L,55,{width:R-L,align:'right'});doc.fillColor(dark)}
  function footer(pageNum){doc.font('Helvetica').fontSize(7).fillColor(muted).text(`${docNo}  |  Rev. 00  |  Generated ${new Date().toLocaleDateString('id-ID')}`,L,H-28,{width:R-L-70});doc.text(`Page ${pageNum}`,R-60,H-28,{width:60,align:'right'});doc.moveTo(L,H-34).lineTo(R,H-34).strokeColor('#d9e2ea').stroke();doc.fillColor(dark)}
  function section(t){if(doc.y>710){doc.addPage();header();doc.y=92}doc.moveDown(.35).font('Helvetica-Bold').fontSize(11).fillColor(blue).text(t);doc.moveDown(.35).fillColor(dark)}
  function box(x,y,w,h,labelTxt,value,sub='',accent=blue){doc.roundedRect(x,y,w,h,6).fillAndStroke('#ffffff','#dce5ed');doc.rect(x,y,4,h).fill(accent);doc.fillColor(muted).font('Helvetica-Bold').fontSize(6.8).text(labelTxt.toUpperCase(),x+12,y+10,{width:w-20});doc.fillColor(dark).fontSize(17).text(String(value),x+12,y+23,{width:w-20});if(sub)doc.font('Helvetica').fontSize(6.8).fillColor(muted).text(sub,x+12,y+h-14,{width:w-20});doc.fillColor(dark)}
  function table(headers,rows,widths,opts={}){const rowH=opts.rowH||18,fontSize=opts.fontSize||7.2;let y=doc.y,total=widths.reduce((a,b)=>a+b,0);function drawHead(){doc.rect(L,y,total,rowH).fill(blue);let x=L;headers.forEach((h,i)=>{doc.fillColor('#fff').font('Helvetica-Bold').fontSize(fontSize).text(h,x+4,y+5,{width:widths[i]-8,height:rowH-6});x+=widths[i]});doc.fillColor(dark);y+=rowH}drawHead();rows.forEach((row,ri)=>{if(y+rowH>H-45){doc.addPage();header();y=92;drawHead()}if(ri%2===0)doc.rect(L,y,total,rowH).fill('#f7f9fb');let x=L;row.forEach((v,i)=>{doc.fillColor(dark).font('Helvetica').fontSize(fontSize).text(String(v??'-'),x+4,y+4,{width:widths[i]-8,height:rowH-5,ellipsis:true});x+=widths[i]});doc.strokeColor('#e2e8ef').moveTo(L,y+rowH).lineTo(L+total,y+rowH).stroke();y+=rowH});doc.y=y+5}
  function barChart(data){if(!data.length){doc.fontSize(8).fillColor(muted).text('Tidak ada pergerakan stok pada periode ini.');doc.fillColor(dark);return}const max=Math.max(1,...data.flatMap(x=>[x.in_qty,x.out_qty])),chartW=R-L-130;data.slice(0,10).forEach(x=>{if(doc.y>700){doc.addPage();header();doc.y=92}const y=doc.y;doc.font('Helvetica').fontSize(7).fillColor(dark).text(x.category,L,y,{width:120,ellipsis:true});const bx=L+125;doc.rect(bx,y,chartW,6).fill('#eef2f6');doc.rect(bx,y,chartW*(x.in_qty/max),6).fill(green);doc.rect(bx,y+8,chartW*(x.out_qty/max),6).fill(red);doc.fontSize(6.5).fillColor(muted).text(`IN ${x.in_qty}   OUT ${x.out_qty}`,bx+chartW+5,y,{width:90});doc.y=y+22});doc.fillColor(dark)}
  header();doc.y=98;doc.font('Helvetica-Bold').fontSize(20).fillColor(blue).text('LAPORAN BULANAN GUDANG & ALAT KERJA');doc.font('Helvetica').fontSize(11).fillColor(muted).text(`Periode ${label}`);doc.moveDown(.4);doc.roundedRect(L,150,R-L,54,6).fillAndStroke(light,'#d2dfeb');doc.fillColor(dark).font('Helvetica-Bold').fontSize(8).text('INFORMASI DOKUMEN',L+12,160);doc.font('Helvetica').fontSize(8).text(`Nomor Dokumen : ${docNo}\nRevisi : 00\nDisiapkan oleh : ${req.user.name} (${req.user.role})`,L+12,174,{columns:2,columnGap:50,width:R-L-24});
  const bw=(R-L-18)/4;let by=224;box(L,by,bw,68,'Jenis Alat',d.items.length,'master item');box(L+bw+6,by,bw,68,'Total Stok',d.items.reduce((a,b)=>a+n(b.stock),0),'unit tersedia',green);box(L+(bw+6)*2,by,bw,68,'Barang Masuk',d.totalIn,`${d.tx.filter(x=>x.tx_type==='IN').length} transaksi`,green);box(L+(bw+6)*3,by,bw,68,'Barang Keluar',d.totalOut,`${d.tx.filter(x=>x.tx_type==='OUT').length} transaksi`,red);by=302;box(L,by,bw,68,'Perlu Restock',d.low.length,'stok ≤ minimum',orange);box(L+bw+6,by,bw,68,'Di Project',d.project.length,'jenis alat',blue);box(L+(bw+6)*2,by,bw,68,'Maintenance',d.maint.length,'jenis alat',orange);box(L+(bw+6)*3,by,bw,68,'Rusak',d.broken.length,'jenis alat',red);doc.y=392;section('Executive Summary');const net=d.totalIn-d.totalOut;doc.font('Helvetica').fontSize(9).fillColor(dark).text(`Pada periode ${label}, tercatat ${d.tx.length} transaksi stok dengan total ${d.totalIn} unit masuk dan ${d.totalOut} unit keluar. Pergerakan bersih periode adalah ${net>=0?'+':''}${net} unit. Saat laporan dibuat terdapat ${d.low.length} item pada atau di bawah minimum stock, ${d.project.length} item berstatus Project, ${d.borrowed.length} Dipinjam, ${d.maint.length} Maintenance, dan ${d.broken.length} Rusak.`,{lineGap:3});section('Pergerakan Stok per Kategori');barChart(d.categories);
  doc.addPage();header('01  INVENTORY STATUS');doc.y=92;section('Posisi Stok & Status Alat');table(['Kode','Nama Alat','Kategori','Stok','Min','Satuan','Status'],d.items.map(i=>[i.code,i.name,i.category||'-',i.stock,i.min_stock,i.unit,i.asset_status]),[62,150,90,38,35,45,87],{fontSize:6.8,rowH:17});
  doc.addPage();header('02  RESTOCK & EXCEPTION');doc.y=92;section('Daftar Prioritas Restock');if(d.low.length)table(['No','Kode','Nama Alat','Kategori','Stok','Minimum','Gap'],d.low.map((i,j)=>[j+1,i.code,i.name,i.category||'-',`${i.stock} ${i.unit}`,i.min_stock,Math.max(0,n(i.min_stock)-n(i.stock))]),[28,65,150,95,62,55,52],{fontSize:7,rowH:18});else doc.fontSize(9).fillColor(green).text('Tidak ada item yang berada pada atau di bawah minimum stock.');section('Maintenance & Rusak');const exceptions=[...d.maint,...d.broken];if(exceptions.length)table(['Kode','Nama','Kategori','Status','Lokasi','Catatan'],exceptions.map(i=>[i.code,i.name,i.category||'-',i.asset_status,i.location||'-',i.notes||'-']),[65,135,90,65,80,74],{fontSize:6.8,rowH:19});else doc.fontSize(9).fillColor(green).text('Tidak ada alat berstatus Maintenance atau Rusak.');
  doc.addPage();header('03  PROJECT DISTRIBUTION');doc.y=92;section('Alat di Project / Dipinjam');const deployed=d.items.filter(i=>['Project','Dipinjam'].includes(i.asset_status));if(deployed.length)table(['Kode','Nama Alat','Status','Project/Tujuan','Holder/PIC','Stok'],deployed.map(i=>[i.code,i.name,i.asset_status,i.current_project||'-',i.current_holder||'-',`${i.stock} ${i.unit}`]),[65,135,65,110,105,55],{fontSize:6.8,rowH:19});else doc.fontSize(9).fillColor(muted).text('Tidak ada alat yang sedang berada di project atau dipinjam.');section('Serah Terima pada Periode');if(d.transfers.length)table(['Tanggal','Kode','Alat','Qty','Project','Penerima','Status'],d.transfers.map(r=>[fmtDateID(r.request_date),r.code,r.item_name,`${r.qty} ${r.unit}`,r.project,r.receiver,r.status]),[58,55,115,50,95,85,65],{fontSize:6.6,rowH:19});else doc.fontSize(9).fillColor(muted).text('Tidak ada pengajuan serah-terima pada periode ini.');
  doc.addPage();header('04  STOCK MOVEMENT');doc.y=92;section('Top 10 Alat Paling Banyak Keluar');if(d.topOut.length)table(['Rank','Kode','Nama Alat','Total Keluar'],d.topOut.map((x,j)=>[j+1,x.code,x.name,`${x.qty} ${x.unit}`]),[45,80,245,100],{fontSize:7.5,rowH:20});else doc.fontSize(9).fillColor(muted).text('Tidak ada transaksi OUT pada periode ini.');section('Detail Transaksi Bulanan');if(d.tx.length)table(['Tanggal','IN/OUT','Kode','Nama Alat','Qty','Sebelum','Sesudah','Tujuan / Sumber','PIC'],d.tx.map(t=>[fmtDateID(t.tx_date),t.tx_type,t.code,t.item_name,`${t.qty}`,t.stock_before,t.stock_after,t.source_target||'-',t.pic||'-']),[48,40,55,110,32,42,42,85,62],{fontSize:6.2,rowH:18});else doc.fontSize(9).fillColor(muted).text('Tidak ada transaksi pada periode ini.');
  doc.addPage();header('05  REVIEW & APPROVAL');doc.y=104;doc.font('Helvetica-Bold').fontSize(12).fillColor(blue).text('Catatan & Tindak Lanjut');doc.moveDown(.5);doc.font('Helvetica').fontSize(9).fillColor(dark).text('1. Lakukan replenishment untuk item yang berada pada atau di bawah minimum stock.\n2. Tindak lanjuti alat berstatus Maintenance/Rusak dan dokumentasikan hasil perbaikan.\n3. Rekonsiliasi alat di project/dipinjam dengan dokumen serah-terima dan PIC.\n4. Pastikan seluruh transaksi stok memiliki nomor dokumen dan PIC yang dapat ditelusuri.',{lineGap:5});doc.y=330;doc.font('Helvetica-Bold').fontSize(11).fillColor(blue).text('Pengesahan Laporan');doc.y=370;const sw=(R-L-20)/3;['Prepared by\nWarehouse','Checked by\nHSE / Project','Approved by\nManagement'].forEach((t,j)=>{let x=L+j*(sw+10);doc.roundedRect(x,doc.y,sw,125,5).strokeColor('#cbd6df').stroke();doc.font('Helvetica-Bold').fontSize(8).fillColor(dark).text(t,x+8,doc.y+12,{width:sw-16,align:'center'});doc.moveTo(x+18,doc.y+92).lineTo(x+sw-18,doc.y+92).strokeColor('#9baab8').stroke();doc.font('Helvetica').fontSize(7).fillColor(muted).text('Nama / Tanggal',x+8,doc.y+98,{width:sw-16,align:'center'})});const range=doc.bufferedPageRange();for(let j=range.start;j<range.start+range.count;j++){doc.switchToPage(j);footer(j-range.start+1)}doc.end();
}));

app.get('/api/admin/backup.json',auth,allow('admin'),ah(async(req,res)=>{const [users,categories,items,transactions,transfers]=await Promise.all([pool.query('SELECT id,name,username,role,active,created_at FROM users ORDER BY id'),pool.query('SELECT * FROM categories ORDER BY id'),pool.query("SELECT id,code,name,category_id,brand,stock,min_stock,unit,condition,location,serial_no,notes,asset_status,current_project,current_holder,updated_at,CASE WHEN photo_data IS NOT NULL THEN encode(photo_data,'base64') ELSE NULL END photo_base64,photo_mime FROM items ORDER BY id"),pool.query("SELECT *,to_char(tx_date,'YYYY-MM-DD') tx_date FROM transactions ORDER BY id"),pool.query("SELECT *,to_char(request_date,'YYYY-MM-DD') request_date FROM transfer_requests ORDER BY id")]);res.setHeader('Content-Disposition',`attachment; filename=GAJA_Backup_${new Date().toISOString().slice(0,10)}.json`);res.json({version:'4.0.0',exported_at:new Date().toISOString(),users:users.rows,categories:categories.rows,items:items.rows,transactions:transactions.rows,transfer_requests:transfers.rows})}));

app.get('/health',ah(async(req,res)=>{await pool.query('SELECT 1');res.json({ok:true,version:'4.0.0',database:'postgresql'})}));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.use((err,req,res,next)=>{console.error(err);if(res.headersSent)return next(err);res.status(500).json({error:'Terjadi kesalahan server. Silakan coba lagi.'})});
initDb().then(()=>app.listen(PORT,()=>console.log(`GAJA Stock Control Pro v4 PostgreSQL running on ${PORT}`))).catch(e=>{console.error('Database initialization failed:',e);process.exit(1)});
