const express=require('express');
const Database=require('better-sqlite3');
const bcrypt=require('bcryptjs');
const jwt=require('jsonwebtoken');
const multer=require('multer');
const QRCode=require('qrcode');
const PDFDocument=require('pdfkit');
const path=require('path');
const fs=require('fs');

const app=express();
const PORT=process.env.PORT||3000;
const JWT_SECRET=process.env.JWT_SECRET||'CHANGE_ME_GAJA_PRODUCTION_SECRET';
const DATA_DIR=process.env.DATA_DIR||path.join(__dirname,'data');
const DB_PATH=process.env.DB_PATH||path.join(DATA_DIR,'warehouse.db');
const UPLOAD_DIR=process.env.UPLOAD_DIR||path.join(DATA_DIR,'uploads');
fs.mkdirSync(DATA_DIR,{recursive:true}); fs.mkdirSync(UPLOAD_DIR,{recursive:true});
const db=new Database(DB_PATH); db.pragma('journal_mode = WAL'); db.pragma('foreign_keys = ON');

db.exec(`
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('admin','warehouse','viewer')),active INTEGER NOT NULL DEFAULT 1,created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS categories(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE NOT NULL,created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS items(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT UNIQUE NOT NULL,name TEXT NOT NULL,category_id INTEGER,brand TEXT DEFAULT '',stock INTEGER NOT NULL DEFAULT 0,min_stock INTEGER NOT NULL DEFAULT 0,unit TEXT DEFAULT 'Unit',condition TEXT DEFAULT 'Baik',location TEXT DEFAULT '',serial_no TEXT DEFAULT '',notes TEXT DEFAULT '',photo_path TEXT DEFAULT '',asset_status TEXT DEFAULT 'Gudang',current_project TEXT DEFAULT '',current_holder TEXT DEFAULT '',updated_at TEXT DEFAULT (datetime('now')),FOREIGN KEY(category_id) REFERENCES categories(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,tx_date TEXT NOT NULL,tx_type TEXT NOT NULL CHECK(tx_type IN ('IN','OUT')),item_id INTEGER NOT NULL,qty INTEGER NOT NULL,stock_before INTEGER NOT NULL,stock_after INTEGER NOT NULL,source_target TEXT DEFAULT '',pic TEXT DEFAULT '',document_no TEXT DEFAULT '',notes TEXT DEFAULT '',created_by INTEGER,created_at TEXT DEFAULT (datetime('now')),FOREIGN KEY(item_id) REFERENCES items(id),FOREIGN KEY(created_by) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS transfer_requests(id INTEGER PRIMARY KEY AUTOINCREMENT,request_date TEXT NOT NULL,item_id INTEGER NOT NULL,qty INTEGER NOT NULL,project TEXT NOT NULL,receiver TEXT NOT NULL,document_no TEXT DEFAULT '',purpose TEXT DEFAULT '',status TEXT NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','APPROVED','REJECTED','RETURNED')),requested_by INTEGER NOT NULL,approved_by INTEGER,approval_note TEXT DEFAULT '',approved_at TEXT,created_at TEXT DEFAULT (datetime('now')),FOREIGN KEY(item_id) REFERENCES items(id),FOREIGN KEY(requested_by) REFERENCES users(id),FOREIGN KEY(approved_by) REFERENCES users(id));
CREATE INDEX IF NOT EXISTS idx_items_category ON items(category_id);
CREATE INDEX IF NOT EXISTS idx_tx_date ON transactions(tx_date);
CREATE INDEX IF NOT EXISTS idx_req_status ON transfer_requests(status);
`);

if(!db.prepare('SELECT COUNT(*) c FROM users').get().c){db.prepare('INSERT INTO users(name,username,password_hash,role) VALUES(?,?,?,?)').run('Administrator','admin',bcrypt.hashSync('Admin123!',10),'admin');}
['Power Tools','Hand Tools','Safety Equipment','Lifting Equipment','Electrical','Consumable'].forEach(x=>db.prepare('INSERT OR IGNORE INTO categories(name) VALUES(?)').run(x));

app.use(express.json({limit:'2mb'})); app.use('/uploads',express.static(UPLOAD_DIR)); app.use(express.static(path.join(__dirname,'public')));
const storage=multer.diskStorage({destination:(req,file,cb)=>cb(null,UPLOAD_DIR),filename:(req,file,cb)=>{const ext=path.extname(file.originalname||'').toLowerCase()||'.jpg';cb(null,`item_${Date.now()}_${Math.random().toString(16).slice(2)}${ext}`)}});
const upload=multer({storage,limits:{fileSize:5*1024*1024},fileFilter:(req,file,cb)=>cb(null,/image\/(png|jpeg|webp)/.test(file.mimetype))});

function auth(req,res,next){const h=req.headers.authorization||'';const t=h.startsWith('Bearer ')?h.slice(7):null;if(!t)return res.status(401).json({error:'Unauthorized'});try{req.user=jwt.verify(t,JWT_SECRET);next()}catch(e){res.status(401).json({error:'Session expired'})}}
const allow=(...roles)=>(req,res,next)=>roles.includes(req.user.role)?next():res.status(403).json({error:'Akses ditolak'});
function itemRow(id){return db.prepare(`SELECT i.*,c.name category FROM items i LEFT JOIN categories c ON c.id=i.category_id WHERE i.id=?`).get(id)}
function logTx({date,type,item,qty,target,pic,doc,notes,userId}){const before=item.stock,after=type==='IN'?before+qty:before-qty;if(after<0)throw new Error('Stok tidak cukup');db.prepare('UPDATE items SET stock=?,updated_at=datetime(\'now\') WHERE id=?').run(after,item.id);db.prepare(`INSERT INTO transactions(tx_date,tx_type,item_id,qty,stock_before,stock_after,source_target,pic,document_no,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run(date,type,item.id,qty,before,after,target||'',pic||'',doc||'',notes||'',userId);return after}

app.post('/api/login',(req,res)=>{const {username,password}=req.body||{};const u=db.prepare('SELECT * FROM users WHERE username=? AND active=1').get(username);if(!u||!bcrypt.compareSync(password||'',u.password_hash))return res.status(401).json({error:'Username atau password salah'});const user={id:u.id,name:u.name,username:u.username,role:u.role};res.json({token:jwt.sign(user,JWT_SECRET,{expiresIn:'12h'}),user})});
app.get('/api/me',auth,(req,res)=>res.json({user:req.user}));
app.get('/api/dashboard',auth,(req,res)=>{const base=db.prepare(`SELECT COUNT(*) item_count,COALESCE(SUM(stock),0) stock_total,SUM(CASE WHEN stock<=min_stock THEN 1 ELSE 0 END) low_count,SUM(CASE WHEN asset_status='Maintenance' THEN 1 ELSE 0 END) maintenance_count FROM items`).get();const ym=new Date().toISOString().slice(0,7);const monthTx=db.prepare('SELECT COUNT(*) c FROM transactions WHERE substr(tx_date,1,7)=?').get(ym).c;const pending=db.prepare("SELECT COUNT(*) c FROM transfer_requests WHERE status='PENDING'").get().c;const recent=db.prepare(`SELECT t.*,i.code,i.name item_name,u.name creator_name FROM transactions t JOIN items i ON i.id=t.item_id LEFT JOIN users u ON u.id=t.created_by ORDER BY t.tx_date DESC,t.id DESC LIMIT 8`).all();const alerts=db.prepare(`SELECT i.id,i.code,i.name,i.stock,i.min_stock,i.unit,i.asset_status,c.name category FROM items i LEFT JOIN categories c ON c.id=i.category_id WHERE i.stock<=i.min_stock OR i.asset_status IN ('Maintenance','Rusak') ORDER BY CASE WHEN i.stock=0 THEN 0 ELSE 1 END,i.stock`).all();res.json({...base,monthTx,pending,recent,alerts})});

app.get('/api/categories',auth,(req,res)=>res.json(db.prepare('SELECT c.*,COUNT(i.id) item_count FROM categories c LEFT JOIN items i ON i.category_id=c.id GROUP BY c.id ORDER BY c.name').all()));
app.post('/api/categories',auth,allow('admin','warehouse'),(req,res)=>{try{const r=db.prepare('INSERT INTO categories(name) VALUES(?)').run((req.body.name||'').trim());res.json({id:r.lastInsertRowid})}catch(e){res.status(400).json({error:'Kategori tidak valid / sudah ada'})}});
app.put('/api/categories/:id',auth,allow('admin','warehouse'),(req,res)=>{try{db.prepare('UPDATE categories SET name=? WHERE id=?').run((req.body.name||'').trim(),req.params.id);res.json({ok:true})}catch(e){res.status(400).json({error:'Kategori tidak valid / sudah ada'})}});
app.delete('/api/categories/:id',auth,allow('admin'),(req,res)=>{if(db.prepare('SELECT COUNT(*) c FROM items WHERE category_id=?').get(req.params.id).c)return res.status(400).json({error:'Kategori masih digunakan'});db.prepare('DELETE FROM categories WHERE id=?').run(req.params.id);res.json({ok:true})});

app.get('/api/items',auth,(req,res)=>res.json(db.prepare(`SELECT i.*,c.name category FROM items i LEFT JOIN categories c ON c.id=i.category_id ORDER BY i.name`).all()));
app.post('/api/items',auth,allow('admin','warehouse'),(req,res)=>{const b=req.body;if(!b.code?.trim()||!b.name?.trim())return res.status(400).json({error:'Kode dan nama alat wajib'});try{const r=db.prepare(`INSERT INTO items(code,name,category_id,brand,stock,min_stock,unit,condition,location,serial_no,notes,asset_status,current_project,current_holder) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(b.code.trim(),b.name.trim(),b.category_id||null,b.brand||'',+b.stock||0,+b.min_stock||0,b.unit||'Unit',b.condition||'Baik',b.location||'',b.serial_no||'',b.notes||'',b.asset_status||'Gudang',b.current_project||'',b.current_holder||'');res.json({id:r.lastInsertRowid})}catch(e){res.status(400).json({error:'Kode alat sudah digunakan / data tidak valid'})}});
app.put('/api/items/:id',auth,allow('admin','warehouse'),(req,res)=>{const b=req.body;try{db.prepare(`UPDATE items SET code=?,name=?,category_id=?,brand=?,stock=?,min_stock=?,unit=?,condition=?,location=?,serial_no=?,notes=?,asset_status=?,current_project=?,current_holder=?,updated_at=datetime('now') WHERE id=?`).run(b.code.trim(),b.name.trim(),b.category_id||null,b.brand||'',+b.stock||0,+b.min_stock||0,b.unit||'Unit',b.condition||'Baik',b.location||'',b.serial_no||'',b.notes||'',b.asset_status||'Gudang',b.current_project||'',b.current_holder||'',req.params.id);res.json({ok:true})}catch(e){res.status(400).json({error:'Data item tidak valid / kode sudah digunakan'})}});
app.delete('/api/items/:id',auth,allow('admin'),(req,res)=>{if(db.prepare('SELECT COUNT(*) c FROM transactions WHERE item_id=?').get(req.params.id).c)return res.status(400).json({error:'Item memiliki histori transaksi'});db.prepare('DELETE FROM items WHERE id=?').run(req.params.id);res.json({ok:true})});
app.post('/api/items/:id/photo',auth,allow('admin','warehouse'),upload.single('photo'),(req,res)=>{if(!req.file)return res.status(400).json({error:'File foto tidak valid'});const old=db.prepare('SELECT photo_path FROM items WHERE id=?').get(req.params.id);db.prepare('UPDATE items SET photo_path=?,updated_at=datetime(\'now\') WHERE id=?').run('/uploads/'+req.file.filename,req.params.id);if(old?.photo_path){try{fs.unlinkSync(path.join(UPLOAD_DIR,path.basename(old.photo_path)))}catch(e){}}res.json({photo_path:'/uploads/'+req.file.filename})});
app.get('/api/items/:id/qr',auth,async(req,res)=>{const i=itemRow(req.params.id);if(!i)return res.status(404).end();const base=process.env.PUBLIC_URL||`${req.protocol}://${req.get('host')}`;const payload=`${base}/?asset=${encodeURIComponent(i.code)}`;res.type('png');res.send(await QRCode.toBuffer(payload,{width:420,margin:2}))});

app.get('/api/transactions',auth,(req,res)=>res.json(db.prepare(`SELECT t.*,i.code,i.name item_name,i.unit,u.name creator_name FROM transactions t JOIN items i ON i.id=t.item_id LEFT JOIN users u ON u.id=t.created_by ORDER BY t.tx_date DESC,t.id DESC`).all()));
app.post('/api/transactions',auth,allow('admin','warehouse'),(req,res)=>{const b=req.body,qty=+b.qty;try{const run=db.transaction(()=>{const i=db.prepare('SELECT * FROM items WHERE id=?').get(b.item_id);if(!i||qty<=0)throw new Error('Data transaksi tidak valid');const after=logTx({date:b.tx_date,type:b.tx_type,item:i,qty,target:b.source_target,pic:b.pic,doc:b.document_no,notes:b.notes,userId:req.user.id});if(b.tx_type==='IN'&&b.set_status)db.prepare(`UPDATE items SET asset_status=?,current_project=?,current_holder=? WHERE id=?`).run(b.set_status,b.set_status==='Project'?(b.source_target||''):'',b.set_status==='Dipinjam'?(b.pic||''):'',i.id);return after});res.json({stock_after:run()})}catch(e){res.status(400).json({error:e.message})}});

app.get('/api/transfers',auth,(req,res)=>res.json(db.prepare(`SELECT r.*,i.code,i.name item_name,i.unit,ru.name requester,au.name approver FROM transfer_requests r JOIN items i ON i.id=r.item_id LEFT JOIN users ru ON ru.id=r.requested_by LEFT JOIN users au ON au.id=r.approved_by ORDER BY r.id DESC`).all()));
app.post('/api/transfers',auth,allow('admin','warehouse'),(req,res)=>{const b=req.body;if(!b.item_id||+b.qty<=0||!b.project?.trim()||!b.receiver?.trim())return res.status(400).json({error:'Alat, jumlah, project, dan penerima wajib diisi'});const i=db.prepare('SELECT stock FROM items WHERE id=?').get(b.item_id);if(!i||+b.qty>i.stock)return res.status(400).json({error:'Stok tidak mencukupi'});const r=db.prepare(`INSERT INTO transfer_requests(request_date,item_id,qty,project,receiver,document_no,purpose,requested_by) VALUES(?,?,?,?,?,?,?,?)`).run(b.request_date,b.item_id,+b.qty,b.project.trim(),b.receiver.trim(),b.document_no||'',b.purpose||'',req.user.id);res.json({id:r.lastInsertRowid})});
app.post('/api/transfers/:id/approve',auth,allow('admin'),(req,res)=>{try{db.transaction(()=>{const r=db.prepare('SELECT * FROM transfer_requests WHERE id=?').get(req.params.id);if(!r||r.status!=='PENDING')throw new Error('Request tidak dapat diproses');const i=db.prepare('SELECT * FROM items WHERE id=?').get(r.item_id);if(r.qty>i.stock)throw new Error('Stok saat approval tidak mencukupi');logTx({date:r.request_date,type:'OUT',item:i,qty:r.qty,target:r.project,pic:r.receiver,doc:r.document_no,notes:'Approved handover: '+r.purpose,userId:req.user.id});db.prepare(`UPDATE transfer_requests SET status='APPROVED',approved_by=?,approval_note=?,approved_at=datetime('now') WHERE id=?`).run(req.user.id,req.body.note||'',r.id);db.prepare(`UPDATE items SET asset_status='Project',current_project=?,current_holder=? WHERE id=?`).run(r.project,r.receiver,r.item_id)})() ;res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/transfers/:id/reject',auth,allow('admin'),(req,res)=>{const r=db.prepare("UPDATE transfer_requests SET status='REJECTED',approved_by=?,approval_note=?,approved_at=datetime('now') WHERE id=? AND status='PENDING'").run(req.user.id,req.body.note||'',req.params.id);if(!r.changes)return res.status(400).json({error:'Request tidak dapat ditolak'});res.json({ok:true})});
app.post('/api/transfers/:id/return',auth,allow('admin','warehouse'),(req,res)=>{try{db.transaction(()=>{const r=db.prepare('SELECT * FROM transfer_requests WHERE id=?').get(req.params.id);if(!r||r.status!=='APPROVED')throw new Error('Request belum approved / sudah dikembalikan');const i=db.prepare('SELECT * FROM items WHERE id=?').get(r.item_id);logTx({date:req.body.return_date,type:'IN',item:i,qty:r.qty,target:'Gudang',pic:req.user.name,doc:r.document_no,notes:'Pengembalian dari '+r.project,userId:req.user.id});db.prepare("UPDATE transfer_requests SET status='RETURNED' WHERE id=?").run(r.id);db.prepare("UPDATE items SET asset_status='Gudang',current_project='',current_holder='' WHERE id=?").run(r.item_id)})() ;res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});

app.get('/api/users',auth,allow('admin'),(req,res)=>res.json(db.prepare('SELECT id,name,username,role,active,created_at FROM users ORDER BY name').all()));
app.post('/api/users',auth,allow('admin'),(req,res)=>{const b=req.body;if(!b.name||!b.username||!b.password)return res.status(400).json({error:'Data user belum lengkap'});try{const r=db.prepare('INSERT INTO users(name,username,password_hash,role) VALUES(?,?,?,?)').run(b.name,b.username,bcrypt.hashSync(b.password,10),b.role);res.json({id:r.lastInsertRowid})}catch(e){res.status(400).json({error:'Username sudah digunakan'})}});
app.put('/api/users/:id',auth,allow('admin'),(req,res)=>{const b=req.body;if(b.password)db.prepare('UPDATE users SET name=?,role=?,active=?,password_hash=? WHERE id=?').run(b.name,b.role,b.active?1:0,bcrypt.hashSync(b.password,10),req.params.id);else db.prepare('UPDATE users SET name=?,role=?,active=? WHERE id=?').run(b.name,b.role,b.active?1:0,req.params.id);res.json({ok:true})});

app.get('/api/reports/monthly.pdf',auth,(req,res)=>{const month=req.query.month||new Date().toISOString().slice(0,7);const tx=db.prepare(`SELECT t.*,i.code,i.name item_name,i.unit,u.name creator FROM transactions t JOIN items i ON i.id=t.item_id LEFT JOIN users u ON u.id=t.created_by WHERE substr(t.tx_date,1,7)=? ORDER BY t.tx_date,t.id`).all(month);const items=db.prepare(`SELECT i.*,c.name category FROM items i LEFT JOIN categories c ON c.id=i.category_id ORDER BY i.name`).all();const doc=new PDFDocument({size:'A4',margin:36});res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`attachment; filename=GAJA_Laporan_Stok_${month}.pdf`);doc.pipe(res);doc.fontSize(17).text('PT GRAHA ADHI JAYA ABADI',{align:'center'});doc.fontSize(13).text('LAPORAN BULANAN STOK ALAT KERJA',{align:'center'});doc.fontSize(10).text(`Periode: ${month}`,{align:'center'}).moveDown();const totalIn=tx.filter(x=>x.tx_type==='IN').reduce((a,b)=>a+b.qty,0),totalOut=tx.filter(x=>x.tx_type==='OUT').reduce((a,b)=>a+b.qty,0);doc.fontSize(10).text(`Total jenis alat: ${items.length} | Total masuk: ${totalIn} unit | Total keluar: ${totalOut} unit | Perlu restock: ${items.filter(x=>x.stock<=x.min_stock).length}`).moveDown();doc.fontSize(12).text('Rekap Stok Saat Ini').moveDown(.4);doc.fontSize(8);items.forEach((i,n)=>{if(doc.y>750)doc.addPage();doc.text(`${n+1}. ${i.code} - ${i.name} | ${i.category||'-'} | Stok ${i.stock} ${i.unit} | Min ${i.min_stock} | ${i.asset_status}`)});doc.addPage();doc.fontSize(12).text('Transaksi Bulan Berjalan').moveDown(.5);doc.fontSize(8);if(!tx.length)doc.text('Tidak ada transaksi.');tx.forEach((t,n)=>{if(doc.y>750)doc.addPage();doc.text(`${n+1}. ${t.tx_date} | ${t.tx_type} | ${t.code} ${t.item_name} | Qty ${t.qty} | ${t.source_target||'-'} | PIC ${t.pic||'-'} | ${t.creator||'-'}`)});doc.end()});

app.get('/health',(req,res)=>res.json({ok:true,version:'2.0.0'}));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(PORT,()=>console.log(`GAJA Stock Control Pro running on ${PORT}`));
